---
# Setup PHP on System
# Adding PHP repository
- name: Add PHP repo
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo

# Enable repo for PHP
- name: enable remi-php
  shell: yum-config-manager --enable remi-php{{php}}

# Installing PHP
- name: Install PHP 
  yum: name={{item}} state=installed
  with_items:
    - php-fpm
    - php 
    - php-devel
    - epel-release
# Remove httpd
- name: remove httpd
  yum: name=httpd state=absent

# install nginx
- name: install nginx
  yum: name=nginx state=installed

# Configure nginx
- name: config nginx
  template: src=default.conf_redhat.j2 dest=/etc/nginx/conf.d/default.conf

# Configure php-fpm
- name: configure php-fpm
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf
  notify:
    - restart nginx
    - restart php-fpm

- name: enable script for php
  shell: echo '<?php phpinfo(); ?>' > /usr/share/nginx/html/info.php
